<?php
/*
 * 列表页表格设置
 * */
namespace app\common\controller;

use think\Controller;
use think\Request;
use Closure;
use app\admin\model\Menu;
use app\common\controller\Tool;

class Table extends Controller{
    protected $model;
    protected $thead=[];

    protected $limit=10;
    protected $where='';
    protected $order="id desc";
    public $createAction=true;
    protected $operate=[
        'editAction'=>true,
        'deleteAction'=>true,
    ];
    protected $tool=[];
    protected $search=[];

    public function _initialize()
    {

        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->sreach=request()->param('get.key','');

    }
    /*
     * 初始华
     * */
    public function init($model){
        $this->model=$model;
    }
    /*
     * 设置表头
     * $fild:字段名
     * $name:字段别名
     * $btn：按钮[字段值=>按钮样式]
     * */
    public function column($fild,$name,$btn=""){
        $thead=$this->thead;
        $new =[
            'id'=>$fild,
            'name'=>$name,
            'btn'=>$btn
        ];
        array_push($thead,$new);
        $this->thead=$thead;
    }
    /*
     * 设置每页条数
     * */
    public function limit($limit){
        $this->limit=$limit;
    }
    /*
     * 设置筛选条件
     * */
    public function where($where){
        $this->where=$where;
    }
    /*
     * 设置排序
     * */
    public function order($order){
        $this->order=$order;
        return $this;
    }
    /*
     * 搜索过滤器设置
     * */
    public function searchs(Closure $callback,$class){
        call_user_func($callback);
        $from=$class->get_from();
        $where=$class->get_where();
        $this->search=$from;
        $this->where=$where;

    }
    /*
     * 工具设置
     * */
    public function tool(Closure $callback,$class){

        $tool=new Tool();

        call_user_func($callback);
        $tool=$class->get_tool();
        $this->tool=$tool;

    }
    /*
     * 修改按钮隐藏
     * */
    public function editAction(){
        unset($this->operate['editAction']);
    }
    /*
     * 删除按钮隐藏
     * */
    public function deleteAction(){
        unset($this->operate['deleteAction']);
    }


    /*
     * 初始化输出表格
     * */
    public function start(){
        $model=$this->model;
        $list=$model->where($this->where)
            ->order($this->order)
            ->paginate($this->limit,false,[
                "query"=>input('get.')
            ]);

        $action=request()->action();
        $controller=request()->controller();
        $route=$controller.'/'.$action;
        $menu=(new Menu)->where(['route'=>$route])->find();
        if($menu['parent_id']!=0){
            $menu2=db('menu')->where('id',$menu['parent_id'])->value('name');
        }
        $dele_url=url($controller.'/'.'dele');
        $create_url=$controller.'/'.'create';

        return view('../../common/view/table/index',[
            'thead'=>$this->thead,
            'token'=>request()->token(),
            'list'=>$list,
            'dele_url'=>$dele_url,
            'create_url'=>$create_url,
            'menu'=>$menu,
            'menu2'=>$menu2,
            'route'=>$route,
            'operate'=>$this->operate,
            'createAction'=>$this->createAction,
            'search'=>$this->search,
            'tool'=>$this->tool
        ]);
    }
}